### ISSUE TITLE
Possibly allow deleting copy-to email

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#518]
this is part of the who to email section, and creator + copyTo email are auto added.  how hard would it be to let people delete the copyTo email?  Submitter email says required.

**Comment by laholstege** [comment]
@srkirkland could probably just add it to the additional emails state, instead of treating it separately. then just remove the logic in AdditonalEmailsHelper that adds the copy email. this would also remove the logic that automatically adds a copy-to found in labworks that isn't already in the list of additional emails (which happens when request number is added)
the only weird thing is if they change client ids. right now, they are automatically updated if you change the client id. this way, they'd have to manually remove an old copy-to if they switch. 

otherwise, we can let them delete the copy to and actually have it remove the value in orderDetails.ClientInfo, and then just don't add copy-to when adding request numbers.
